# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30716e7bcbde1d4ecf2f8e009edf26eefbcc359f35f22a07892103465870dff1619dad05a11845312cf6749da84f57b6eb74ff117f1e4980b208a437e6d9d86

test:
  secret_key_base: 6c165228be3a4e881c2c8fbb294cd3b79c219bea5626c2a07096daab5e50d0cbd90f1871e82baf54905d97f8d8d8cbacd5a411f60c50f4a544bd12a20743dbe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
